name: tateworld
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1
  go_router: ^14.3.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.1.0
  pocketbase: ^0.18.1
  image_picker: ^0.8.4+3
  provider: ^6.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  permission_handler: ^11.3.1
  sqflite: ^2.0.0+3
  path: ^1.8.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

dev_dependencies:
  flutter_native_splash: ^2.2.7

flutter_native_splash:
  color: "#ffffff"                      
  image: assets/app_icon.png            
  android: true
  ios: true
  web: false
  title: "TaTe World"                   
  title_color: "#000000"                
  title_font_size: 24.0                 
  title_padding: 30.0                   
  android_gravity: center               
  ios_content_mode: scaleAspectFit
  android_scale_type: centerCrop       

